SUBDIRS = mpi mpid util basic commands .
smvar_do_sharedlibs = 0
smvarSubdir_commonmake=
distclean-local:
	rm -f runtests

# Test both the MPI routines and the MPICH2 command scripts
testing:
	(cd mpi && $(MAKE) testing)
	(cd commands && $(MAKE) testing)
