SUBDIRS = mpi mpid util .
smvar_do_sharedlibs = 0
distclean-local:
	rm -f runtests

testing:
	./runtests -srcdir=$(srcdir) -tests=testlist \
		   -mpiexec=$(bindir)/mpiexec \
		   -xmlfile=summary.xml
