LDADD = -L../../../lib -lmpich
INCLUDES = -I../../../src/include -I${top_srcdir}/src/include -I../include

typename_SOURCES = typename.c

contents_SOURCES = contents.c

struct-pack_SOURCES = triangular-pack.c

triangular-pack_SOURCES = triangular-pack.c

slice-pack_SOURCES = slice-pack.c

simple-pack_SOURCES = simple-pack.c

transpose-pack_SOURCES = transpose-pack.c

lbub_SOURCES = lbub.c

