LDADD = -L../../../lib -lmpich
INCLUDES = -I../../../src/include -I${top_srcdir}/src/include -I../include
smvar_do_sharedlibs = 0

typename_SOURCES = typename.c

contents_SOURCES = contents.c

struct-pack_SOURCES = struct-pack.c

triangular-pack_SOURCES = triangular-pack.c

slice-pack_SOURCES = slice-pack.c

simple-pack_SOURCES = simple-pack.c

transpose-pack_SOURCES = transpose-pack.c

localpack_SOURCES = localpack.c

lbub_SOURCES = lbub.c

zeroparms_SOURCES = zeroparms.c
