LDADD = -L../../../lib -lmpich
INCLUDES = -I../../../src/include -I${top_srcdir}/src/include -I../include \
	 -I${srcdir}/../include
smvar_do_sharedlibs = 0

typename_SOURCES = typename.c

contents_SOURCES = contents.c

struct-pack_SOURCES = struct-pack.c

triangular-pack_SOURCES = triangular-pack.c

slice-pack_SOURCES = slice-pack.c

slice-pack-external_SOURCES = slice-pack-external.c

simple-pack_SOURCES = simple-pack.c

simple-pack-external_SOURCES = simple-pack-external.c

subarray-pack_SOURCES = subarray-pack.c

transpose-pack_SOURCES = transpose-pack.c

localpack_SOURCES = localpack.c

lbub_SOURCES = lbub.c

zeroparms_SOURCES = zeroparms.c
gaddress_SOURCES = gaddress.c
gaddress_LDADD = ../util/mtest.o

getpartelm_SOURCES = getpartelm.c
getpartelm_LDADD = ../util/mtest.o

tresized_SOURCES = tresized.c
tresized_LDADD = ../util/mtest.o 

tmatchsize_SOURCES = tmatchsize.c
tmatchsize_LDADD = ../util/mtest.o 

tresized2_SOURCES = tresized2.c
tresized2_LDADD = ../util/mtest.o 

tfree_SOURCES = tfree.c
tfree_LDADD = ../util/mtest.o 
		 
../util/mtest.o:
	(cd ../util && $(MAKE) mtest.o )
