smvar_do_sharedlibs = 0
INCLUDES = -I../../include -I${srcdir}/../../include
LDADD = ../util/mtest.o 
DEPADD = ../util/mtest.o

spawnargvx_SOURCES  = spawnargvx.cxx
spawnintrax_SOURCES = spawnintrax.cxx
namepubx_SOURCES    = namepubx.cxx
