lib${MPILIBNAME}_a_SOURCES = getpname.c pcontrol.c version.c
INCLUDES = -I../../include -I${top_srcdir}/src/include
profilelib_${MPILIBNAME} = p${MPILIBNAME}
doc_HTML_SOURCES = getpname.c pcontrol.c version.c
