# Generated automatically from Makefile.in by configure.
CC          = /homes/jlee/mpich2/bin/mpicc
AR          = ar crl
LIBNAME     = /homes/jlee/mpich2/lib/libmpich.a
MPI         = mpich
srcdir      = /homes/jlee/mpich2/src/mpi/romio/adio/ad_ln
CC_SHL      = true
SHLIBNAME   = /homes/jlee/mpich2/lib/libmpich

INCLUDE_DIR = -I. -I${srcdir}/../include -I../include -I${srcdir}/../../../../include -I../../../../include
CFLAGS      =  -I/homes/jlee/mpich2/src/binding/f77 -I/homes/jlee/mpich2/src/binding/f77 -I/homes/jlee/mpich2/src/mpid/ch3/include -I/homes/jlee/mpich2/src/mpid/ch3/include -I/homes/jlee/mpich2/src/mpid/common/datatype -I/homes/jlee/mpich2/src/mpid/common/datatype -I/homes/jlee/mpich2/src/mpid/common/locks -I/homes/jlee/mpich2/src/mpid/common/locks -I/homes/jlee/mpich2/src/mpid/ch3/channels/sock/include -I/homes/jlee/mpich2/src/mpid/ch3/channels/sock/include -I/homes/jlee/mpich2/src/mpid/common/sock -I/homes/jlee/mpich2/src/mpid/common/sock -I/homes/jlee/mpich2/src/mpid/common/sock/poll -I/homes/jlee/mpich2/src/mpid/common/sock/poll -O2 -g -Wall -I/home/jlee/lors-0.82.1/local/include -O2 -g -Wall -I/home/jlee/lors-0.82.1/local/include -DFORTRANDOUBLEUNDERSCORE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -DHAVE_ROMIOCONF_H $(INCLUDE_DIR)

C_COMPILE_SHL = $(CC_SHL) -O2 -g -Wall -I/home/jlee/lors-0.82.1/local/include -O2 -g -Wall -I/home/jlee/lors-0.82.1/local/include -DFORTRANDOUBLEUNDERSCORE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -DHAVE_ROMIOCONF_H $(INCLUDE_DIR)

VPATH = .:${srcdir}

AD_LN_OBJECTS = ad_ln_close.o ad_ln_read.o ad_ln_rdcoll.o \
	ad_ln_wrcoll.o ad_ln_open.o ad_ln_write.o \
	ad_ln_done.o ad_ln_fcntl.o ad_ln_iread.o \
	ad_ln_iwrite.o ad_ln_wait.o ad_ln_flush.o \
	ad_ln_resize.o ad_ln_delete.o ad_ln_libxio.o ad_ln.o

default: $(LIBNAME)
	@if [ "none" != "none" ] ; then \
	    $(MAKE) $(SHLIBNAME).la ;\
	fi

.SUFFIXES: $(SUFFIXES) .p .lo

.c.o:
	$(CC) $(CFLAGS) -c $<
.c.lo:
	$(C_COMPILE_SHL) $(INC) -c $<
	@mv -f $*.o $*.lo

$(LIBNAME): $(AD_LN_OBJECTS)
	$(AR) $(LIBNAME) $(AD_LN_OBJECTS)

AD_LN_LOOBJECTS = $(AD_LN_OBJECTS:.o=.lo)

$(SHLIBNAME).la: $(AD_LN_LOOBJECTS)
	$(AR) $(SHLIBNAME).la $(AD_LN_LOOBJECTS)

clean:
	@rm -f *.o *.lo
tags: TAGS
SOURCES = ${AD_LN_OBJECTS:.o=.c}
HEADERS = 
TAGS:${HEADERS} ${SOURCES}
	here=`cd ../../../../.. && pwd` ; cd ${srcdir} && etags -o $$here/TAGS --append ${HEADERS} ${SOURCES}
