INCLUDES = -I../include -I${top_srcdir}/include
smvar_do_sharedlibs = 0

LDADD = -L../../../lib ../util/mtest.o
dup_SOURCES      = dup.c
dupic_SOURCES    = dupic.c
ic1_SOURCES      = ic1.c
cfree_SOURCES    = cfree.c
commname_SOURCES = commname.c
ctxalloc_SOURCES = ctxalloc.c
