SUBDIRS = . src examples test
all-local:
	if [ ! -d lib ] ; then mkdir lib ; fi
all-preamble:
	@echo "Beginning make"
all-postamble:
	@echo "Make completed"
distclean-local:
	-@rm -f lib/libmpich.a
	-@rm -f src/include/mpichconf.h

install_LIB = lib/libmpich.a
optinstall_LIB = lib/libpmpich.a
optinstall_SHLIB = lib/libmpich.so
#install_DOC = 
#install_HTML = 
#install_MAN = 
#install_BIN = 
#install_SBIN = 	
