#!/bin/sh

mpi_datatype_prefix="4c00"

#
# C datatype sizes
#
len_short="02"
len_int="04"
len_long="04"
len_long_long="08"
len_float="04"
len_double="08"
len_long_double="08"
len_wchar_t="02"
len_float_int="08"
len_double_int="10"
len_long_int="08"
len_short_int="08"
len_2_int="08"
len_long_double_int="10"

MPI_CHAR="0x${mpi_datatype_prefix}0101"
MPI_UNSIGNED_CHAR="0x${mpi_datatype_prefix}0102"
MPI_SHORT="0x${mpi_datatype_prefix}${len_short}03"
MPI_UNSIGNED_SHORT="0x${mpi_datatype_prefix}${len_short}04"
MPI_INT="0x${mpi_datatype_prefix}${len_int}05"
MPI_UNSIGNED_INT="0x${mpi_datatype_prefix}${len_int}06"
MPI_LONG="0x${mpi_datatype_prefix}${len_long}07"
MPI_UNSIGNED_LONG="0x${mpi_datatype_prefix}${len_long}08"
MPI_LONG_LONG="0x${mpi_datatype_prefix}${len_long_long}09"
MPI_FLOAT="0x${mpi_datatype_prefix}${len_float}0b"
MPI_DOUBLE="0x${mpi_datatype_prefix}${len_double}0d"
MPI_LONG_DOUBLE="0x${mpi_datatype_prefix}${len_long_double}0f"
MPI_BYTE="0x${mpi_datatype_prefix}0111"
MPI_WCHAR_T="0x${mpi_datatype_prefix}${len_wchar_t}13"
MPI_PACKED="0x${mpi_datatype_prefix}0114"
MPI_LB="0x${mpi_datatype_prefix}0015"
MPI_UB="0x${mpi_datatype_prefix}0016"
#
# These should define the mixed types *only* for contiguous data.
# For example, MPI_SHORT_INT may have a gap; it will need to be defined
# as a derived type instead.  For IA32, this only affects short_int.
#
MPI_FLOAT_INT="0x${mpi_datatype_prefix}${len_float_int}17"
MPI_DOUBLE_INT="0x${mpi_datatype_prefix}${len_double_int}18"
MPI_LONG_INT="0x${mpi_datatype_prefix}${len_long_int}19"
MPI_SHORT_INT="0x${mpi_datatype_prefix}${len_short_int}1a"
MPI_2INT="0x${mpi_datatype_prefix}${len_2_int}1b"
MPI_LONG_DOUBLE_INT="0x${mpi_datatype_prefix}${len_long_double_int}1c"

#
# Fortran datatype sizes
#
len_integer="08"
len_double="08"
len_doublecplx="10"
len_2dc="20"

MPI_CHARACTER=0x${mpi_datatype_prefix}0120
MPI_INTEGER=0x${mpi_datatype_prefix}${len_integer}21
MPI_REAL=0x${mpi_datatype_prefix}${len_integer}22
MPI_LOGICAL=0x${mpi_datatype_prefix}${len_integer}23
MPI_COMPLEX=0x${mpi_datatype_prefix}${len_double}24
MPI_DOUBLE_PRECISION=0x${mpi_datatype_prefix}${len_double}25
MPI_2INTEGER=0x${mpi_datatype_prefix}${len_double}26
MPI_2REAL=0x${mpi_datatype_prefix}${len_double}27
MPI_DOUBLE_COMPLEX=0x${mpi_datatype_prefix}${len_doublecplx}28
MPI_2DOUBLE_PRECISION=0x${mpi_datatype_prefix}${len_doublecplx}29
MPI_2COMPLEX=0x${mpi_datatype_prefix}${len_doublecplx}2a
MPI_2DOUBLE_COMPLEX=0x${mpi_datatype_prefix}${len_2dc}2b

#
# Miscellaneous settings
#
MPI_MAX_PROCESSOR_NAME=128
BSEND_OVERHEAD=52
MPI_AINT="int"
MPI_FINT="int"
MPI_OFFSET="__int64"
EXTRA_STATUS_DECL=
#HAVE_ROMIO=#include "mpio.h"
HAVE_ROMIO=

#
# Create mpi.h for windows
#
sed 's/%@/@@/; s/@%/@@/; s/%g$/@g/; /@g$/s/[\\&%]/\\&/g; s/@@/%@/; s/@@/@%/; s/@g$/%g/' > conftest.subs <<CEOF
s%@MPI_CHAR@%${MPI_CHAR}%g
s%@MPI_UNSIGNED_CHAR@%${MPI_UNSIGNED_CHAR}%g
s%@MPI_SHORT@%${MPI_SHORT}%g
s%@MPI_UNSIGNED_SHORT@%${MPI_UNSIGNED_SHORT}%g
s%@MPI_INT@%${MPI_INT}%g
s%@MPI_UNSIGNED_INT@%${MPI_UNSIGNED_INT}%g
s%@MPI_LONG@%${MPI_LONG}%g
s%@MPI_UNSIGNED_LONG@%${MPI_UNSIGNED_LONG}%g
s%@MPI_LONG_LONG@%${MPI_LONG_LONG}%g
s%@MPI_FLOAT@%${MPI_FLOAT}%g
s%@MPI_DOUBLE@%${MPI_DOUBLE}%g
s%@MPI_LONG_DOUBLE@%${MPI_LONG_DOUBLE}%g
s%@MPI_BYTE@%${MPI_BYTE}%g
s%@MPI_WCHAR_T@%${MPI_WCHAR_T}%g
s%@MPI_PACKED@%${MPI_PACKED}%g
s%@MPI_LB@%${MPI_LB}%g
s%@MPI_UB@%${MPI_UB}%g
s%@MPI_FLOAT_INT@%${MPI_FLOAT_INT}%g
s%@MPI_DOUBLE_INT@%${MPI_DOUBLE_INT}%g
s%@MPI_LONG_INT@%${MPI_LONG_INT}%g
s%@MPI_SHORT_INT@%${MPI_SHORT_INT}%g
s%@MPI_2INT@%${MPI_2INT}%g
s%@MPI_LONG_DOUBLE_INT@%${MPI_LONG_DOUBLE_INT}%g
s%@MPI_CHARACTER@%${MPI_CHARACTER}%g
s%@MPI_INTEGER@%${MPI_INTEGER}%g
s%@MPI_REAL@%${MPI_REAL}%g
s%@MPI_LOGICAL@%${MPI_LOGICAL}%g
s%@MPI_COMPLEX@%${MPI_COMPLEX}%g
s%@MPI_DOUBLE_PRECISION@%${MPI_DOUBLE_PRECISION}%g
s%@MPI_2INTEGER@%${MPI_2INTEGER}%g
s%@MPI_2REAL@%${MPI_2REAL}%g
s%@MPI_DOUBLE_COMPLEX@%${MPI_DOUBLE_COMPLEX}%g
s%@MPI_2DOUBLE_PRECISION@%${MPI_2DOUBLE_PRECISION}%g
s%@MPI_2COMPLEX@%${MPI_2COMPLEX}%g
s%@MPI_2DOUBLE_COMPLEX@%${MPI_2DOUBLE_COMPLEX}%g
s%@MPI_MAX_PROCESSOR_NAME@%${MPI_MAX_PROCESSOR_NAME}%g
s%@BSEND_OVERHEAD@%${BSEND_OVERHEAD}%g
s%@MPI_AINT@%${MPI_AINT}%g
s%@MPI_FINT@%${MPI_FINT}%g
s%@MPI_OFFSET@%${MPI_OFFSET}%g
s%@EXTRA_STATUS_DECL@%${EXTRA_STATUS_DECL}%g
s%@HAVE_ROMIO@%${HAVE_ROMIO}%g
CEOF

sed -f conftest.subs <src/include/mpi.h.in >src/include/mpi.h
rm -f conftest.subs
