INCLUDES = -I../../../src/include -I${top_srcdir}/src/include -I../include \
	 -I${srcdir}/../include
LDADD = -L../../../lib ../util/mtest.o
DEPADD = ../../../lib/lib${MPILIBNAME}.a
smvar_do_sharedlibs = 0

# isendirecv contains features that not all systems support (e.g., the
# sincos call, not available on IRIX).
EXTRA_PROGRAMS = 
exitst1_SOURCES = exitst1.c
exitst2_SOURCES = exitst2.c
exitst3_SOURCES = exitst3.c
initstat_SOURCES = initstat.c 
version_SOURCES = version.c
timeout_SOURCES = timeout.c
