mpi_sources = 

lib${MPILIBNAME}_a_SOURCES = dbginit.c
INCLUDES = -I../../include -I${top_srcdir}/src/include
profilelib_${MPILIBNAME} = p${MPILIBNAME}
#
# This is a test for the document generation
doc_HTML_SOURCES  = 
doc_MAN_SOURCES   = 
doc_LATEX_SOURCES =

