INCLUDES = -I../../../src/include -I${top_srcdir}/src/include -I../include \
	 -I${srcdir}/../include
LDADD = -L../../../lib ../util/mtest.o 
DEPADD = ../../../lib/lib${MPILIBNAME}.a
smvar_do_sharedlibs = 0

infodup_SOURCES = infodup.c
infodel_SOURCES = infodel.c
infovallen_SOURCES = infovallen.c
infoorder_SOURCES = infoorder.c
infomany_SOURCES = infomany.c
infotest_SOURCES = infotest.c

../util/mtest.o:
	(cd ../util && $(MAKE) mtest.o)
