INCLUDES = -I../../include -I${master_top_srcdir}/src/include \
    -I../../pmi/simple -I${master_top_srcdir}/src/pmi/simple

#libmpiexec_a_SOURCES = cmnargs.c pmiserv.c timelimit.c sigs.c iohandlers.c \
#	newsession.c rm.c
libmpiexec_a_SOURCES = cmnargs.c process.c ioloop.c pmiserv.c

OTHER_DIRS = test

distclean-local:

