INCLUDES = -I../../../src/include -I${top_srcdir}/src/include -I../include \
	 -I${srcdir}/../include
LDADD = -L../../../lib ../util/mtest.o 
DEPADD = ../../../lib/lib${MPILIBNAME}.a
smvar_do_sharedlibs = 0

EXTRA_PROGRAMS = 
rdwrord_SOURCES = rdwrord.c
rdwrzero_SOURCES = rdwrzero.c
getextent_SOURCES = getextent.c
setinfo_SOURCES = setinfo.c
