LDADD = -L../../../../lib ../util/mtestf.o 
DEPADD = ../../../../lib/lib${MPILIBNAME}.a ../util/mtestf.o
smvar_do_sharedlibs = 0

uallreducef_SOURCES  = uallreducef.f
exscanf_SOURCES     = exscanf.f
alltoallwf_SOURCES  = alltoallwf.f

../util/mtestf.o: 
	(cd ../util && $(MAKE) mtestf.o)
