LDADD = -L../../../../lib ../util/mtestf.o 
DEPADD = ../../../../lib/lib${MPILIBNAME}.a
smvar_do_sharedlibs = 0

uallreduce_SOURCES = uallreduce.f

../util/mtestf.o: 
	(cd ../util && $(MAKE) mtestf.o)
