INCLUDES = -I../../../src/include -I${top_srcdir}/src/include -I../include \
	 -I${srcdir}/../include
LDADD = -L../../../lib ../util/mtest.o 
DEPADD = ../../../lib/lib${MPILIBNAME}.a
smvar_do_sharedlibs = 0

namepub_SOURCES = namepub.c
spawn1_SOURCES = spawn1.c
