INCLUDES = -I../include -I${srcdir}/../include
LDADD = ../util/mtest.o 
DEPADD = @MPILIBLOC@ ../util/mtest.o
smvar_do_sharedlibs = 0

namepub_SOURCES = namepub.c
spawn1_SOURCES = spawn1.c
spawn2_SOURCES = spawn2.c
spawnintra_SOURCES = spawnintra.c
spawnargv_SOURCES = spawnargv.c
spaconacc_SOURCES = spaconacc.c
selfconacc_SOURCES = selfconacc.c
spawnmult2_SOURCES = spawnmult2.c
join_SOURCES = join.c
disconnect_reconnect_SOURCES = disconnect_reconnect.c
disconnect_reconnect2_SOURCES = disconnect_reconnect2.c
multiple_ports_SOURCES = multiple_ports.c
spaiccreate_SOURCES = spaiccreate.c

../util/mtest.o:
	(cd ../util && $(MAKE) mtest.o)

testing:
	../runtests -srcdir=$(srcdir) -tests=testlist \
			-mpiexec=$(bindir)/mpiexec \
		   	-xmlfile=summary.xml
