INCLUDES = -I../../../../include -I${master_top_srcdir}/src/include
lib${MPILIBNAME}_a_SOURCES = sock.c socki_describe_states.c

sock.o: sock.c sock_init.i sock_set.i sock_post.i sock_immed.i sock_misc.i sock_wait.i socki_util.i ../mpidu_sock.h mpidu_socki.h
