stdiotest_SOURCES = stdiotest.c
rtest_SOURCES     = rtest.c
rtestf_SOURCES    = rtestf.f
rtestx_SOURCES    = rtestx.cxx

MPICC = $(bindir)/mpicc
MPICXX = $(bindir)/mpicxx
MPIF77 = $(bindir)/mpif77

.c.o:
	$(MPICC) -c $<
.f.o:
	$(MPIF77) -c $<
.F.o:
	$(MPIF77) -c $<
.cxx.o:
	$(MPICXX) -c $<

testing:
	./cmdtests

