F77INCLUDES = -I. 
LDADD = ../util/mtestf.o 
DEPADD = @MPILIBLOC@ ../util/mtestf.o
smvar_do_sharedlibs = 0

namepubf_SOURCES = namepubf.f
spawnf_SOURCES = spawnf.f
spawnargvf_SOURCES = spawnargvf.f
spawnmultf_SOURCES = spawnmultf.f
spawnmult2f_SOURCES = spawnmult2f.f
connaccf_SOURCES = connaccf.f

../util/mtestf.o: 
	(cd ../util && $(MAKE) mtestf.o)
