lib${MPILIBNAME}_a_SOURCES = infoutil.c info_create.c info_delete.c \
 info_dup.c info_free.c info_get.c info_getn.c info_getnth.c \
 info_getvallen.c info_set.c info_delete.c
INCLUDES = -I../../include -I${top_srcdir}/src/include
