#!/bin/sh
SLOG2_AUTOHEADER=${SLOG2_AUTOHEADER:-"autoheader"}
SLOG2_AUTOCONF=${SLOG2_AUTOCONF:-"autoconf"}
AUTOHEADER=${AUTOHEADER:-${SLOG2_AUTOHEADER}}
AUTOCONF=${AUTOCONF:-${SLOG2_AUTOCONF}}

# The directory of this script is located
PWD=`pwd`
curr_dir="$PWD/`dirname $0`"
# The parent directory of where this script is located
master_dir="`dirname $curr_dir`"

# Locate all the configure.in under master_dir
cfgins=`find $master_dir -name 'configure.in' -print`
for cfgin in $cfgins ; do
    dir="`dirname $cfgin`"
    echo "Creating configure in $dir/ ..."
    cd $dir
    if [ -n "`grep AC_CONFIG_HEADER $cfgin`" ] ; then
        $AUTOHEADER
    fi
    $AUTOCONF
done
