INCLUDES = -I../../../src/include -I${top_srcdir}/src/include -I../include \
	 -I${srcdir}/../include
LDADD = -L../../../lib ../util/mtest.o 
DEPADD = ../../../lib/lib${MPILIBNAME}.a
smvar_do_sharedlibs = 0

# isendirecv contains features that not all systems support (e.g., the
# sincos call, not available on IRIX).
EXTRA_PROGRAMS = bsend1cxx isendirecv
bsend1_SOURCES = bsend1.c
bsend2_SOURCES = bsend2.c
bsend3_SOURCES = bsend3.c
bsend4_SOURCES = bsend4.c
bsendalign_SOURCES = bsendalign.c
isendself_SOURCES = isendself.c
bsend1cxx_SOURCES = bsend1cxx.cxx
bsendfrag_SOURCES = bsendfrag.c
errinstatts_SOURCES = errinstatts.c
errinstatta_SOURCES = errinstatta.c
errinstatws_SOURCES = errinstatws.c
errinstatwa_SOURCES = errinstatwa.c
icsend_SOURCES = icsend.c
rqstatus_SOURCES = rqstatus.c
greq1_SOURCES = greq1.c
