LDADD = -L../../../../lib ../util/mtestf.o 
DEPADD = ../../../../lib/lib${MPILIBNAME}.a ../util/mtestf.o
smvar_do_sharedlibs = 0

# allocmem_SOURCES = allocmem.f
winscale1f_SOURCES = winscale1f.f
winscale2f_SOURCES = winscale2f.f
winfencef_SOURCES  = winfencef.f
winerrf_SOURCES    = winerrf.f
winattrf_SOURCES   = winattrf.f
winnamef_SOURCES   = winnamef.f
wingroupf_SOURCES  = wingroupf.f
winaccf_SOURCES    = winaccf.f

../util/mtestf.o: 
	(cd ../util && $(MAKE) mtestf.o)
