INCLUDES = -I../include -I${top_srcdir}/include
LDADD = -L../../../lib ../util/mtest.o 
DEPADD = ../../../lib/lib${MPILIBNAME}.a
smvar_do_sharedlibs = 0

adderr_SOURCES = adderr.c
errstring_SOURCES = errstring.c
errcode_SOURCES = errcode.c errmsg.c
errring_SOURCES = errring.c
commcall_SOURCES = commcall.c
winerr_SOURCES = winerr.c
