# This is temporary until the tests have their own configure
errstring_SOURCES = errstring.c
errstring_LDADD = -L ../../../lib -lmpich
INCLUDES = -I../../../src/include -I${top_srcdir}/src/include -I../include
