INCLUDES = -I../include -I${top_srcdir}/include
LDADD = -L../../../lib 
DEPADD = ../../../lib/lib${MPILIBNAME}.a
smvar_do_sharedlibs = 0

errstring_SOURCES = errstring.c
errcode_SOURCES = errcode.c errmsg.c
errring_SOURCES = errring.c
