INCLUDES = -I../../include -I${srcdir}/../../include
LDADD = ../../util/mtest.o
threaded_sr_LDADD = -lpthread 
DEPADD = @MPILIBLOC@ ../../util/mtest.o
smvar_do_sharedlibs = 0

# Use extra programs to list programs that should not be built by default.
EXTRA_PROGRAMS       = 

threaded_sr_SOURCES  = threaded_sr.c
alltoall_SOURCES = alltoall.c
sendself_SOURCES = sendself.c

../../util/mtest.o:
	(cd ../../util && $(MAKE) mtest.o)
