/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


#ifdef F77_NAME_UPPER
#define mpirinitc_ MPIRINITC
#elif defined(F77_NAME_LOWER_2USCORE) || defined(F77_NAME_LOWER_USCORE)
/* leave name alone */
#else
#define mpirinitc_ mpirinitc
#endif

#if defined(F77_RUNTIME_VALUES) || !defined(F77_TRUE_VALUE_SET)
MPI_Fint MPIR_F_TRUE = 1, MPIR_F_FALSE = 0;
#endif

#ifndef USE_POINTER_FOR_BOTTOM
void *MPIR_F_MPI_BOTTOM     = 0;
void *MPI_F_STATUS_IGNORE   = 0;
void *MPI_F_STATUSES_IGNORE = 0;
#endif


FORTRAN_API void FORT_CALL mpirinitc_( void *a, void *b, void *c )
{
    MPIR_F_MPI_BOTTOM     = a;
    MPI_F_STATUS_IGNORE   = b;
    MPI_F_STATUSES_IGNORE = c;
}
