/* -*- Mode: C; c-basic-offset:4 ; -*- */
/*  
 *  (C) 2001 by Argonne National Laboratory.
 *      See COPYRIGHT in top-level directory.
 *
 * This file is automatically generated by buildiface 
 * DO NOT EDIT
 */
#include "mpi_fortimpl.h"


#ifdef F77_NAME_UPPER
#define mpirinitc_ MPIRINITC
#elif defined(F77_NAME_LOWER_2USCORE) || defined(F77_NAME_LOWER_USCORE)
/* leave name alone */
#else
#define mpirinitc_ mpirinitc
#endif

FORTRAN_API void FORT_CALL mpirinitc_( void *a, void *b, void *c )
{
    MPIR_F_MPI_BOTTOM = a;
    MPIR_F_MPI_STATUS_IGNORE = b;
    MPIR_F_MPI_STATUSES_IGNORE = c;
}
