INCLUDES = -I../../../src/include -I${top_srcdir}/src/include -I../../include \
	 -I${srcdir}/../../include
LDADD = -L../../../lib ../util/mtest.o 
smvar_do_sharedlibs = 0

attrt_SOURCES = attrtx.cxx
#attric_SOURCES = attricx.cxx
#attrerr_SOURCES = attrerrx.cxx
#attrerrcomm_SOURCES = attrerrcommx.cxx
#attrerrtype_SOURCES = attrerrtypex.cxx
#attrorder_SOURCES = attrorderx.cxx
#attrordercomm_SOURCES = attrordercommx.cxx
#attrordertype_SOURCES = attrordertypex.cxx
#attrorderwin_SOURCES = attrorderwinx.cxx
#baseattr2_SOURCES = baseattr2x.cxx
baseattrcommx_SOURCES = baseattrcommx.cxx
#baseattrwin_SOURCES = baseattrwinx.cxx
fkeyvalcommx_SOURCES = fkeyvalcommx.cxx
fkeyvaltypex_SOURCES = fkeyvaltypex.cxx
fkeyvalwinx_SOURCES = fkeyvalwinx.cxx 

../util/mtest.o:
	(cd ../util && $(MAKE) mtest.o)
