# As routines are implemented, add there files to the list.
# (unimplemented routines should cause link-time, not run-time failures)
lib${MPILIBNAME}_a_SOURCES = comm_rank.c comm_size.c commutil.c
#lib${MPILIBNAME}_a_SOURCES = comm_compare.c \
    comm_create.c comm_dup.c comm_free.c comm_group.c comm_remote_group.c \
    comm_remote_size.c \
    comm_split.c comm_test_inter.c comm_get_name.c comm_set_name.c \
    intercomm_create.c intercomm_merge.c
INCLUDES = -I../../include -I${top_srcdir}/src/include
