mpi_sources = abort.c init.c initialized.c initthread.c \
 ismain.c finalize.c finalized.c querythread.c
HEADERS = mpi_init.h
lib${MPILIBNAME}_a_SOURCES = ${mpi_sources}
profilelib_${MPILIBNAME} = p${MPILIBNAME}
INCLUDES = -I../../include -I${top_srcdir}/src/include
#
doc_HTML_SOURCES = ${mpi_sources}
doc_MAN_SOURCES = ${mpi_sources}
doc_LATEX_SOURCES = ${mpi_sources}
