INCLUDES = -I../../../src/include -I${top_srcdir}/src/include -I../include
LDADD = -L../../../lib
DEPADD = ../../../lib/lib${MPILIBNAME}.a
smvar_do_sharedlibs = 0

self_SOURCES = self.c
simple_SOURCES = simple.c
sendrecv_SOURCES = sendrecv.c
srtest_SOURCES = srtest.c
wtime_SOURCES = wtime.c
netpipe_SOURCES = netmpi.c GetOpt.c
patterns_SOURCES = patterns.c
adapt_SOURCES = adapt.c GetOpt.c
