LDADD = -L ../../../lib 
self_SOURCES = self.c
DEPADD = ../../../lib/libmpich.a
simple_SOURCES = simple.c
sendrecv_SOURCES = sendrecv.c
srtest_SOURCES = srtest.c
wtime_SOURCES = wtime.c
netpipe_SOURCES = netmpi.c GetOpt.c
patterns_SOURCES = patterns.c

INCLUDES = -I../../../src/include -I${top_srcdir}/src/include -I../include
DEPADD = ../../../lib/libmpich.a
