simple_SOURCES = simple.c
simple_LDADD = -L ../../../lib -lmpich
sendrecv_SOURCES = sendrecv.c
sendrecv_LDADD = -L ../../../lib -lmpich
INCLUDES = -I../../../src/include -I${top_srcdir}/src/include -I../include
