LDADD = -L../../../../lib ../util/mtestf.o 
DEPADD = ../../../../lib/lib${MPILIBNAME}.a ../util/mtestf.o
smvar_do_sharedlibs = 0

statusesf_SOURCES = statusesf.f

../util/mtestf.o: 
	(cd ../util && $(MAKE) mtestf.o)
