# LIBS includes -lmpich and other libraries (e.g., -lpmpich if
# weak symbols are not supported)
INCLUDES = -I../../../src/include -I${top_srcdir}/src/include
EXTERNAL_LIBS = m
LDADD = -L../../../lib
DEPADD = ../../../lib/lib${MPILIBNAME}.a
#
cpi_SOURCES = cpi.c
cpi_LDADD = -lm -lpthread
test1_SOURCES = test1.c
test1_LDADD = -lpthread
test2_SOURCES = test2.c
test2_LDADD = -lpthread
test3_SOURCES = test3.c
test3_LDADD = -lpthread
test4_SOURCES = test4.c
test4_LDADD = -lpthread
transpose1_SOURCES = transpose1.c
transpose1_LDADD = -lpthread
transpose2_SOURCES = transpose2.c
transpose2_LDADD = -lpthread
transpose3_SOURCES = transpose3.c
transpose3_LDADD = -lpthread
transpose4_SOURCES = transpose4.c
transpose4_LDADD = -lpthread
fetchandadd_SOURCES = fetchandadd.c
fetchandadd_LDADD = -lpthread
fetchandadd_tree_SOURCES = fetchandadd_tree.c
fetchandadd_tree_LDADD = -lpthread
