# LIBS includes -lmpich and other libraries (e.g., -lpmpich if
# weak symbols are not supported)
INCLUDES = -I../include -I${top_srcdir}/include
EXTERNAL_LIBS = m
LDADD = -L../../../lib
DEPADD = ../../../lib/lib${MPILIBNAME}.a
smvar_do_sharedlibs = 0
#
cpi_SOURCES = cpi.c
cpi_LDADD = -lm
test1_SOURCES = test1.c
test2_SOURCES = test2.c
test3_SOURCES = test3.c
test4_SOURCES = test4.c
transpose1_SOURCES = transpose1.c
transpose2_SOURCES = transpose2.c
transpose3_SOURCES = transpose3.c
transpose4_SOURCES = transpose4.c
fetchandadd_SOURCES = fetchandadd.c
fetchandadd_tree_SOURCES = fetchandadd_tree.c
