# LIBS includes -lmpich and other libraries (e.g., -lpmpich if
# weak symbols are not supported)
bcasttest_SOURCES = bcasttest.c
bcasttest_LDADD = -L ../../../lib
allred_SOURCES = allred.c
allred_LDADD = -L ../../../lib
coll8_SOURCES = coll8.c
coll8_LDADD = -L ../../../lib
coll13_SOURCES = coll13.c
coll13_LDADD = -L ../../../lib
alltoallv_SOURCES = alltoallv.c
alltoallv_LDADD = -L ../../../lib
INCLUDES = -I../../../src/include -I${top_srcdir}/src/include
