# LIBS includes -lmpich and other libraries (e.g., -lpmpich if
# weak symbols are not supported)
INCLUDES = -I../../../src/include -I${top_srcdir}/src/include -I../include \
	 -I${srcdir}/../include
EXTERNAL_LIBS = m
LDADD = -L../../../lib
DEPADD = ../../../lib/lib${MPILIBNAME}.a
smvar_do_sharedlibs = 0
#
bcasttest_SOURCES = bcasttest.c
bcast2_SOURCES = bcast2.c
allred_SOURCES = allred.c
allred_LDADD = -lm
coll8_SOURCES = coll8.c
coll13_SOURCES = coll13.c
alltoallv_SOURCES = alltoallv.c
alltoall1_SOURCES = alltoall1.c
redscat_SOURCES = redscat.c
coll9_SOURCES = coll9.c
coll7_SOURCES = coll7.c
coll6_SOURCES = coll6.c
coll5_SOURCES = coll5.c
coll4_SOURCES = coll4.c
coll3_SOURCES = coll3.c
coll2_SOURCES = coll2.c
allredmany_SOURCES = allredmany.c
scantst_SOURCES = scantst.c
longuser_SOURCES = longuser.c
coll10_SOURCES = coll10.c
coll11_SOURCES = coll11.c
coll12_SOURCES = coll12.c
scatterv_SOURCES = scatterv.c
scattern_SOURCES = scattern.c
rerr_SOURCES = rerr.c
icbcast_SOURCES = icbcast.c
icbcast_LDADD = ../util/mtest.o
icallreduce_SOURCES = icallreduce.c
icallreduce_LDADD = ../util/mtest.o
icreduce_SOURCES = icreduce.c
icreduce_LDADD = ../util/mtest.o
bcast2_LDADD = ../util/mtest.o
alltoall1_LDADD = ../util/mtest.o
opland_SOURCES = opland.c
opland_LDADD = ../util/mtest.o
oplor_SOURCES = oplor.c
oplor_LDADD = ../util/mtest.o
opsum_SOURCES = opsum.c
opsum_LDADD = ../util/mtest.o
