INCLUDES = -I../../../src/include -I${top_srcdir}/src/include -I../include \
	 -I${srcdir}/../include
LDADD = -L../../../lib ../util/mtest.o 
DEPADD = ../../../lib/lib${MPILIBNAME}.a
smvar_do_sharedlibs = 0

attrt_SOURCES = attrt.c
attrict_SOURCES = attrict.c
attrerr_SOURCES = attrerr.c
attrerrcomm_SOURCES = attrerrcomm.c
attrerrtype_SOURCES = attrerrtype.c
attrorder_SOURCES = attrorder.c
attrordercomm_SOURCES = attrordercomm.c
attrordertype_SOURCES = attrordertype.c
attrorderwin_SOURCES = attrorderwin.c
baseattr2_SOURCES = baseattr2.c
baseattrcomm_SOURCES = baseattrcomm.c
baseattrwin_SOURCES = baseattrwin.c
fkeyval_SOURCES = fkeyval.c
fkeyvalcomm_SOURCES = fkeyvalcomm.c
fkeyvaltype_SOURCES = fkeyvaltype.c
fkeyvalwin_SOURCES = fkeyvalwin.c 


