INCLUDES = -I../../include -I${master_top_srcdir}/src/include \
    -I../../pmi/simple -I${master_top_srcdir}/src/pmi/simple
mpiexec_LDADD = -L../../../lib -L${master_top_srcdir}/lib -lmpich
mpiexec_SOURCES = mpiexec.c rm.c cmnargs.c pmiserv.c sigs.c timelimit.c waitfor.c 

install_BIN = mpiexec
distclean-local:
	@-rm -f remshellconf.h

mpich2-build-install: install

mpich2-build-uninstall: uninstall
