# This is temporary until the tests have their own configure
infotest_SOURCES = infotest.c
infotest_LDADD = -L../../../lib @EXAMPLE_LIBS@
infomany_SOURCES = infomany.c
infomany_LDADD = -L../../../lib @EXAMPLE_LIBS@
INCLUDES = -I../../../src/include -I${top_srcdir}/src/include
