#! /usr/bin/perl
# -*- Mode: perl; -*-
#
# This is a simple script to clean up the output from make by removing
# various compilation options (such as the list of -I directories), 
# -W options for gcc, and successful compiles.
$last_line = "";
while (<>) {
    # skip lines that start with for and are continued.
    if (/^\s*for dir in .*\\$/) {
	while (<>) {
	    if (! /\\$/) { last; }
	}
    }
    # skip line that start with if and ar continued
    if (/^\s*if \[ ! -d lib.*\\$/) {
	while (<>) {
	    if (! /\\$/) { last; }
	}
    }

    if (/^[agi]?cc\s/) {
	s/-I[^\s]*\s*//g;
	s/-DHAVE_CONFIG_H\s*//g;
    }
    if (/^[agi]?c\+\+\s/ || /^CC\s/) {
	s/-I[^\s]*\s*//g;
	s/-DHAVE_CONFIG_H\s*//g;
    }
    if (/^[-A-Za-z0-9\.\/]*mpicc\s/) {
	s/[-A-Za-z0-9\.\/]*mpicc\s/mpicc /;
	s/-I[^\s]*\s*//g;
	s/-W[^\s]*\s*//g;
	s/-ansi\s*//g;
	s/-DHAVE_CONFIG_H\s*//g;
    }
    if (/^gcc /) {
	s/-W[^\s]*\s*//g;
	s/-ansi\s*//g;
    }
    
    if (/^\s*make /) { next; }

    if (/Nothing to be done for /) {
	next;
    }
    if (/cleaning directory/) {
	next;
    }
    if (/^\s*rm /) { next; }
    
    if (/^\s*ar /) { $_ = "...ar step\n"; }

    # Skip the time adjust step
    if (/^perl -e/) { next; }
    if ($last_line =~ /[^\s]/) { 
	# Decide if we want to print this, based on the current line.
	if ($last_line =~ /^[agi]?cc\s/ || $last_line =~ /^mpicc\s/) {
	    if (! (/^[ag]?cc\s/) && ! (/^mpicc\s/) && ! (/^\.\.\.ar/) ) { 
		# Add a new line to help the compile line stand out.
		print "\n";
		print $last_line; 
	    }
	}
	else {
	    print $last_line;
	}
    }
    $last_line = $_;
}
print $last_line;
