#! /usr/bin/perl
#
# Extract the various parameter names and help strings.
#
require "maint/parse.sub";

#
# Still to be written.  Use GetSubArgs on MPIU_Param_register.
# Parameterize output so that latex, ASCII, or HTML/XML can be generated.
# Share output code with extractconfigopts
#
