#! /usr/bin/perl
#
# Extract the various configure enable and with option helps, since
# configure --usage doesn't descend into the subsidiary configures (!)
#
require "maint/parse.sub";

#
# Still to be written.  Use GetSubArgs on AC_WITH and AC_ENABLE to get the
# help string.  
# Parameterize output so that latex, ASCII, or HTML/XML can be generated.
#
