#! /usr/bin/perl
#
while (<>) {
    if (/^gcc/) {
	$state = "in_cc";
	$cc_line = $_;
	$cc_line_printed = 0;
    }
    else {
	if ($state eq "in_cc") {
	    # It must be a warning or error message
	    if (!$cc_line_printed) {
		print $cc_line;
		$cc_line_printed = 1;
	    }
	    print $_;
	}
	else {
	    $state = "other";
	}
    }
}
