#! /bin/sh
#
# Create simple schedule web pages
# Switch to 4 columns because our print drivers no longer properly resize 
# the page, leading to having some text chopped of.
rm -f .m1 .m2 .m3 mpich2-1pgrs.html
cat schedule | maint/schdtox -html=4 -mpi1 > .m2
cat >>.m1 <<EOF
<HTML>
<HEAD>
<TITLE>MPICH2 Progress: MPI 1 Routines</TITLE>
</HEAD>
<BODY BGCOLOR="FFFFFF">
<H2>Status of MPI-1 Functions in MPICH2</H2>
EOF
cat >>.m3 <<EOF
</BODY>
</HTML>
EOF
cat .m1 .m2 .m3 > mpich2-1pgrs.html
rm -f .m1 .m2 .m3
#
rm -f .m1 .m2 .m3 mpich2-pgrs.html
cat schedule | maint/schdtox -html=4 > .m2
cat >>.m1 <<EOF
<HTML>
<HEAD>
<TITLE>MPICH2 Progress: All MPI Routines</TITLE>
</HEAD>
<BODY BGCOLOR="FFFFFF">
<H2>Status of MPI Functions in MPICH2</H2>
EOF
cat >>.m3 <<EOF
</BODY>
</HTML>
EOF
cat .m1 .m2 .m3 > mpich2-pgrs.html
rm -f .m1 .m2 .m3
