# SUBDIRS_pm_name are the names that @ pm_name @ can take in SUBDIRS
SUBDIRS_pm_name = mpd forker
SUBDIRS = @pm_name@ .
all-postamble:
	build_prefix=`cd ../.. && pwd` && cd @pm_name@ && \
	${MAKE} prefix=$$build_prefix mpich2-build-install
