#include <winsock2.h>

#define SOCK_IOV             WSABUF
#define SOCK_IOV_LEN         len
#define SOCK_IOV_BUF         buf
#define SOCK_IOV_MAXLEN      16
#define SOCK_INFINITE_TIME   INFINITE
#define SOCK_INVALID_SOCKET  NULL
#define SOCK_SIZE_MAX	     INT_MAX

typedef HANDLE sock_set_t;
typedef struct sock_state_t * sock_t;
typedef int sock_size_t;

#define inline __inline

#define MPID_STATE_LIST_SOCK \
MPID_STATE_SOCK_INIT, \
MPID_STATE_SOCK_FINALIZE, \
MPID_STATE_SOCK_CREATE_SET, \
MPID_STATE_SOCK_DESTROY_SET, \
MPID_STATE_SOCK_LISTEN, \
MPID_STATE_SOCK_POST_CONNECT, \
MPID_STATE_SOCK_ACCEPT, \
MPID_STATE_SOCK_POST_CLOSE, \
MPID_STATE_SOCK_WAIT, \
MPID_STATE_SOCK_SET_USER_PTR, \
MPID_STATE_SOCK_READ, \
MPID_STATE_SOCK_READV, \
MPID_STATE_SOCK_WRITE, \
MPID_STATE_SOCK_WRITEV, \
MPID_STATE_SOCK_POST_READ, \
MPID_STATE_SOCK_POST_READV, \
MPID_STATE_SOCK_POST_WRITE, \
MPID_STATE_SOCK_POST_WRITEV, \
MPID_STATE_SOCK_EASY_RECEIVE, \
MPID_STATE_SOCK_EASY_SEND
