# As routines are implemented, add there files to the list.
# (unimplemented routines should cause link-time, not run-time failures)
lib${MPILIBNAME}_a_SOURCES = 
#lib${MPILIBNAME}_a_SOURCES = group_compare.c group_difference.c group_excl.c \
 group_free.c group_incl.c group_intersection.c group_range_excl.c \
 group_range_incl.c \
 group_rank.c group_size.c group_translate_ranks.c group_union.c grouputil.c
INCLUDES = -I../../include -I${top_srcdir}/src/include
