mpi_sources = group_compare.c group_difference.c group_excl.c \
 group_free.c group_incl.c group_intersection.c group_range_excl.c \
 group_range_incl.c group_rank.c group_size.c group_translate_ranks.c \
 group_union.c 
lib${MPILIBNAME}_a_SOURCES = ${mpi_sources} grouputil.c groupdebug.c
INCLUDES = -I../../include -I${top_srcdir}/src/include
profilelib_${MPILIBNAME} = p${MPILIBNAME}
#
# This is a test for the document generation
doc_HTML_SOURCES = ${mpi_sources}

# translate