#SUBDIRS = common tcp via shm viardma progress xfer bsocket mm init spawn pt2pt request util .
SUBDIRS_method_subdirs = tcp shm via viardma sock
SUBDIRS = common @method_subdirs@ progress xfer bsocket mm init spawn pt2pt request util packer unpacker .
