srbtest_SOURCES = srbtest.c
sr_SOURCES      = sr.c
srvec_SOURCES   = srvec.c
#
# Replace the value of CC
prefix          = @prefix@
exec_prefix     = @exec_prefix@
bindir          = @bindir@
CC              = @MPICC@
CPPFLAGS        = 
