#! /bin/sh
AUTOHEADER=${AUTOHEADER:-autoheader}
AUTOCONF=${AUTOCONF:-autoconf}
MPE_AUTOHEADER=${MPE_AUTOHEADER:-$AUTOHEADER}
MPE_AUTOCONF=${MPE_AUTOCONF:-$AUTOCONF}

# The directory of this script is located
# PWD is not guaranteed to be set to the current directory in all cases
# (e.g., in /bin/sh, (cd src/mpe2 && maint/updatefiles won't set
# PWD to .../src/mpe2)
PWD=`pwd`
curr_dir="$PWD/`dirname $0`"
# The parent directory of where this script is located
master_dir="`dirname $curr_dir`"

# Locate all the configure.in under master_dir
cfgins=`find $master_dir -name 'configure.in' -print`
for cfgin in $cfgins ; do
    dir="`dirname $cfgin`"
    echo "Creating configure in $dir/ ..."
    cd $dir
    if [ -n "`grep AC_CONFIG_HEADER $cfgin`" ] ; then
        $MPE_AUTOHEADER
    fi
    $MPE_AUTOCONF
done
