#! /bin/sh
MPE_AUTOHEADER=${MPE_AUTOHEADER:-"autoheader"}
MPE_AUTOCONF=${MPE_AUTOCONF:-"autoconf"}
AUTOHEADER=${AUTOHEADER:-${MPE_AUTOHEADER}}
AUTOCONF=${AUTOCONF:-${MPE_AUTOCONF}}

# The directory of this script is located
# PWD is not guaranteed to be set to the current directory in all cases
# (e.g., in /bin/sh, (cd src/mpe2 && maint/updatefiles won't set
# PWD to .../src/mpe2)
PWD=`pwd`
curr_dir="$PWD/`dirname $0`"
# The parent directory of where this script is located
master_dir="`dirname $curr_dir`"

# Locate all the configure.in under master_dir
cfgins=`find $master_dir -name 'configure.in' -print`
for cfgin in $cfgins ; do
    dir="`dirname $cfgin`"
    echo "Creating configure in $dir/ ..."
    cd $dir
    if [ -n "`grep AC_CONFIG_HEADER $cfgin`" ] ; then
        $AUTOHEADER
    fi
    $AUTOCONF
done
