# As routines are implemented, add there files to the list.
# (unimplemented routines should cause link-time, not run-time failures)
lib${MPILIBNAME}_a_SOURCES = 
#lib${MPILIBNAME}_a_SOURCES = accumulate.c alloc_mem.c free_mem.c get.c put.c \
 win_complete.c win_create.c win_fence.c win_free.c win_get_group.c \
 win_get_name.c \
 win_lock.c win_post.c win_set_name.c win_start.c win_unlock.c win_wait.c \
 winutil.c win_test.c
INCLUDES = -I../../include -I${top_srcdir}/src/include
