smvar_do_sharedlibs = 0
INCLUDES = -I../../../src/include -I${top_srcdir}/src/include -I../../include \
	 -I${srcdir}/../../include
LDADD = ../util/mtest.o 
DEPADD = ../util/mtest.o

commname_SOURCES = commname.cxx

../util/mtest.o:
	(cd ../util && $(MAKE) mtest.o )
